import { ColorScheme, ColorContrast, allColors, withAlpha } from "../shared";

export const getBaseColors = (scheme: ColorScheme, contrast: ColorContrast) => {
	const colors = allColors[scheme];
	const {
		bg1,
		bg2,
		bg3,
		bg4,
		grey,
		fg1,
		fg2,
		fg3,
		fg4,
		red1,
		red2,
		green1,
		green2,
		yellow1,
		yellow2,
		blue1,
		blue2,
		purple1,
		purple2,
		aqua1,
		aqua2,
		orange1,
		orange2,
		transparent,
		white,
	} = colors;
	const bg0 = colors[`bg0_${contrast}`];

	return {
		// BASE COLORS
		focusBorder: bg1,
		foreground: fg1,
		"widget.shadow": withAlpha(bg0, 48),
		"selection.background": withAlpha(aqua1, 128),
		errorForeground: red2,
		"icon.foreground": fg1,
		// BUTTON
		"button.background": withAlpha(blue1, 128),
		"button.foreground": fg1,
		"button.hoverBackground": withAlpha(blue1, 96),
		// DROPDOWN
		"dropdown.background": bg0,
		"dropdown.border": bg1,
		"dropdown.foreground": fg1,
		// INPUT
		"input.background": bg0,
		"input.border": bg1,
		"input.foreground": fg1,
		"input.placeholderForeground": withAlpha(fg1, 96),
		"inputValidation.errorBorder": red2,
		"inputValidation.errorBackground": red1,
		"inputValidation.infoBorder": blue2,
		"inputValidation.infoBackground": withAlpha(blue1, 128),
		"inputValidation.warningBorder": yellow2,
		"inputValidation.warningBackground": yellow1,
		"inputOption.activeBorder": withAlpha(fg1, 96),
		// SCROLL BAR
		"scrollbar.shadow": bg0,
		"scrollbarSlider.activeBackground": aqua1,
		"scrollbarSlider.hoverBackground": bg3,
		"scrollbarSlider.background": withAlpha(bg2, 153),
		// BADGE
		"badge.background": purple1,
		"badge.foreground": white,
		// PROGRESS BAR
		"progressBar.background": aqua1,
		// LISTS AND TREES
		"list.activeSelectionBackground": withAlpha(bg1, 128),
		"list.activeSelectionForeground": aqua2,
		"list.hoverBackground": withAlpha(bg1, 128),
		"list.hoverForeground": fg2,
		"list.focusBackground": bg1,
		"list.focusForeground": fg1,
		"list.inactiveSelectionForeground": aqua1,
		"list.inactiveSelectionBackground": withAlpha(bg1, 128),
		"list.dropBackground": bg1,
		"list.highlightForeground": aqua1,
		// SIDE BAR
		"sideBar.background": bg0,
		"sideBar.foreground": fg2,
		"sideBar.border": bg1,
		"sideBarTitle.foreground": fg1,
		"sideBarSectionHeader.background": transparent,
		"sideBarSectionHeader.foreground": fg1,
		// ACTIVITY BAR
		"activityBar.background": bg0,
		"activityBar.foreground": fg1,
		"activityBar.border": bg1,
		"activityBarTop.background": bg0,
		"activityBarTop.foreground": fg1,
		"activityBarBadge.background": blue1,
		"activityBarBadge.foreground": white,
		// EDITOR GROUPS
		"editorGroup.border": bg1,
		"editorGroup.dropBackground": withAlpha(bg1, 96),
		"editorGroupHeader.noTabsBackground": bg0,
		"editorGroupHeader.tabsBackground": bg0,
		"editorGroupHeader.tabsBorder": bg1,
		// TABS
		"tab.border": transparent,
		"tab.activeBorder": aqua1,
		"tab.activeBackground": bg1,
		"tab.activeForeground": fg1,
		"tab.inactiveForeground": fg4,
		"tab.inactiveBackground": bg0,
		"tab.unfocusedActiveForeground": fg4,
		"tab.unfocusedActiveBorder": transparent,
		"tab.unfocusedInactiveForeground": grey,
		// EDITOR
		"editor.background": bg0,
		"editor.foreground": fg1,
		"editorLineNumber.foreground": bg3,
		"editorCursor.foreground": fg1,
		"editor.selectionBackground": withAlpha(aqua1, 64),
		"editor.selectionHighlightBackground": withAlpha(yellow2, 64),
		"editor.hoverHighlightBackground": withAlpha(aqua1, 80),
		"editorLink.activeForeground": fg1,
		"editor.findMatchBackground": withAlpha(blue2, 112),
		"editor.findMatchHighlightBackground": withAlpha(orange2, 48),
		"editor.findRangeHighlightBackground": withAlpha(blue2, 112),
		"editor.lineHighlightBackground": withAlpha(bg1, 96),
		"editor.lineHighlightBorder": transparent,
		"editorWhitespace.foreground": withAlpha(fg4, 32),
		"editorRuler.foreground": withAlpha(fg4, 64),
		"editorCodeLens.foreground": withAlpha(fg4, 144),
		"editorBracketMatch.border": transparent,
		"editorBracketMatch.background": withAlpha(grey, 128),
		"editorHoverWidget.background": bg0,
		"editorHoverWidget.border": bg1,
		"editorOverviewRuler.border": transparent,
		"editorOverviewRuler.findMatchForeground": fg3,
		"editorOverviewRuler.rangeHighlightForeground": fg3,
		"editorOverviewRuler.selectionHighlightForeground": bg3,
		"editorOverviewRuler.wordHighlightForeground": bg3,
		"editorOverviewRuler.wordHighlightStrongForeground": bg3,
		"editorOverviewRuler.modifiedForeground": blue2,
		"editorOverviewRuler.addedForeground": blue2,
		"editorOverviewRuler.deletedForeground": blue2,
		"editorOverviewRuler.errorForeground": red2,
		"editorOverviewRuler.warningForeground": yellow1,
		"editorOverviewRuler.infoForeground": purple2,
		"editorGutter.background": transparent,
		"editorGutter.modifiedBackground": blue2,
		"editorGutter.addedBackground": green2,
		"editorGutter.deletedBackground": red2,
		"editorError.foreground": red1,
		"editorWarning.foreground": yellow1,
		"editorInfo.foreground": blue1,
		// EDITOR - BRACKET PAIR COLORIZATION
		"editorBracketHighlight.foreground1": purple1,
		"editorBracketHighlight.foreground2": blue1,
		"editorBracketHighlight.foreground3": aqua1,
		"editorBracketHighlight.foreground4": green1,
		"editorBracketHighlight.foreground5": yellow1,
		"editorBracketHighlight.foreground6": orange1,
		"editorBracketHighlight.unexpectedBracket.foreground": red1,
		// EDITOR - STICKY SCROLL
		"editorStickyScroll.shadow": withAlpha(bg2, 153),
		"editorStickyScrollHover.background": withAlpha(bg1, 96),
		// DIFF EDITOR
		"diffEditor.insertedTextBackground": withAlpha(green2, 48),
		"diffEditor.removedTextBackground": withAlpha(red2, 48),
		// WIDGET
		"editorWidget.background": bg0,
		"editorWidget.border": bg1,
		"editorSuggestWidget.background": bg0,
		"editorSuggestWidget.foreground": fg1,
		"editorSuggestWidget.highlightForeground": aqua1,
		"editorSuggestWidget.selectedBackground": withAlpha(bg1, 96),
		"editorSuggestWidget.border": bg1,
		// PEEK VIEW
		"peekView.border": bg1,
		"peekViewEditor.background": withAlpha(bg1, 112),
		"peekViewEditor.matchHighlightBackground": bg2,
		"peekViewEditorGutter.background": withAlpha(bg1, 112),
		"peekViewResult.background": withAlpha(bg1, 112),
		"peekViewResult.fileForeground": fg1,
		"peekViewResult.selectionBackground": withAlpha(blue1, 32),
		"peekViewResult.selectionForeground": fg1,
		"peekViewResult.lineForeground": fg1,
		"peekViewResult.matchHighlightBackground": bg2,
		"peekViewTitle.background": withAlpha(bg1, 112),
		"peekViewTitleDescription.foreground": fg3,
		"peekViewTitleLabel.foreground": fg1,
		// MERGE CONFLICTS
		"merge.currentHeaderBackground": withAlpha(blue1, 64),
		"merge.currentContentBackground": withAlpha(blue1, 32),
		"merge.incomingHeaderBackground": withAlpha(aqua1, 64),
		"merge.incomingContentBackground": withAlpha(aqua1, 32),
		"merge.border": transparent,
		"editorOverviewRuler.currentContentForeground": blue1,
		"editorOverviewRuler.incomingContentForeground": aqua1,
		"editorOverviewRuler.commonContentForeground": grey,
		// PANELS
		"panel.border": bg1,
		"panelTitle.activeForeground": fg1,
		// STATUS BAR
		"statusBar.background": bg0,
		"statusBar.border": bg1,
		"statusBar.foreground": fg1,
		"statusBar.debuggingBackground": orange2,
		"statusBar.debuggingForeground": bg0,
		"statusBar.debuggingBorder": transparent,
		"statusBar.noFolderBackground": bg0,
		"statusBar.noFolderBorder": transparent,
		// INTEGRATED TERMINAL
		"terminal.ansiBlack": bg1,
		"terminal.ansiBrightBlack": grey,
		"terminal.ansiRed": red1,
		"terminal.ansiBrightRed": red2,
		"terminal.ansiGreen": green1,
		"terminal.ansiBrightGreen": green2,
		"terminal.ansiYellow": yellow1,
		"terminal.ansiBrightYellow": yellow2,
		"terminal.ansiBlue": blue1,
		"terminal.ansiBrightBlue": blue2,
		"terminal.ansiMagenta": purple1,
		"terminal.ansiBrightMagenta": purple2,
		"terminal.ansiCyan": aqua1,
		"terminal.ansiBrightCyan": aqua2,
		"terminal.ansiWhite": fg4,
		"terminal.ansiBrightWhite": fg1,
		"terminal.foreground": fg1,
		"terminal.background": bg0,
		// TITLE BAR macOS (not tested)
		"titleBar.activeBackground": bg0,
		"titleBar.activeForeground": fg1,
		"titleBar.inactiveBackground": bg0,
		// GIT COLORS
		"gitDecoration.modifiedResourceForeground": yellow1,
		"gitDecoration.deletedResourceForeground": red1,
		"gitDecoration.untrackedResourceForeground": green1,
		"gitDecoration.ignoredResourceForeground": bg4,
		"gitDecoration.conflictingResourceForeground": purple1,
		// MENU BAR
		"menu.border": bg1,
		"menu.separatorBackground": bg1,
		// EXTENSIONS
		"extensionButton.prominentBackground": withAlpha(green2, 128),
		"extensionButton.prominentHoverBackground": withAlpha(green2, 48),
		// OTHERS
		"textLink.foreground": blue2,
		"textLink.activeForeground": blue1,
		"debugToolBar.background": bg0,
	};
};
