name: pr-checks

on:
  pull_request:

jobs:
  pr-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - name: typecheck
        run: npm run type:check
      - name: lint
        run: npm run lint:check
      - name: format check
        run: npm run format:check
      - name: build check
        run: npm run build
